// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sqrt_fixed_16_6_s (
        ap_clk,
        ap_rst,
        x_V,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [15:0] x_V;
output  [12:0] ap_return;

reg   [15:0] x_V_read_reg_2102;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] x_V_read_reg_2102_pp0_iter1_reg;
reg   [15:0] x_V_read_reg_2102_pp0_iter2_reg;
reg   [15:0] x_V_read_reg_2102_pp0_iter3_reg;
reg   [15:0] x_V_read_reg_2102_pp0_iter4_reg;
reg   [15:0] x_V_read_reg_2102_pp0_iter5_reg;
reg   [15:0] x_V_read_reg_2102_pp0_iter6_reg;
wire   [9:0] trunc_ln731_fu_192_p1;
reg   [9:0] trunc_ln731_reg_2107;
wire   [2:0] select_ln488_2_fu_316_p3;
reg   [2:0] select_ln488_2_reg_2112;
wire   [0:0] icmp_ln488_2_fu_348_p2;
reg   [0:0] icmp_ln488_2_reg_2118;
wire   [8:0] select_ln488_5_fu_372_p3;
reg   [8:0] select_ln488_5_reg_2123;
wire   [0:0] icmp_ln1495_fu_390_p2;
reg   [0:0] icmp_ln1495_reg_2132;
wire   [0:0] icmp_ln318_fu_406_p2;
reg   [0:0] icmp_ln318_reg_2137;
wire   [2:0] select_ln488_4_fu_428_p3;
reg   [2:0] select_ln488_4_reg_2142;
reg   [2:0] select_ln488_4_reg_2142_pp0_iter2_reg;
reg   [2:0] select_ln488_4_reg_2142_pp0_iter3_reg;
reg   [2:0] select_ln488_4_reg_2142_pp0_iter4_reg;
reg   [2:0] select_ln488_4_reg_2142_pp0_iter5_reg;
reg   [2:0] select_ln488_4_reg_2142_pp0_iter6_reg;
wire   [10:0] select_ln318_fu_490_p3;
reg   [10:0] select_ln318_reg_2156;
wire   [8:0] select_ln318_2_fu_506_p3;
reg   [8:0] select_ln318_2_reg_2162;
wire   [8:0] sub_ln703_2_fu_597_p2;
reg   [8:0] sub_ln703_2_reg_2167;
wire   [0:0] or_ln318_1_fu_621_p2;
reg   [0:0] or_ln318_1_reg_2172;
wire   [10:0] select_ln318_4_fu_627_p3;
reg   [10:0] select_ln318_4_reg_2178;
reg   [0:0] tmp_19_reg_2186;
wire   [1:0] trunc_ln708_13_fu_643_p1;
reg   [1:0] trunc_ln708_13_reg_2191;
wire   [10:0] select_ln318_6_fu_772_p3;
reg   [10:0] select_ln318_6_reg_2196;
wire   [10:0] select_ln318_7_fu_780_p3;
reg   [10:0] select_ln318_7_reg_2202;
wire   [8:0] select_ln318_8_fu_787_p3;
reg   [8:0] select_ln318_8_reg_2207;
wire   [0:0] icmp_ln1495_3_fu_826_p2;
reg   [0:0] icmp_ln1495_3_reg_2213;
wire   [10:0] sub_ln703_5_fu_832_p2;
reg   [10:0] sub_ln703_5_reg_2218;
wire   [8:0] add_ln703_3_fu_838_p2;
reg   [8:0] add_ln703_3_reg_2223;
wire   [0:0] or_ln318_3_fu_862_p2;
reg   [0:0] or_ln318_3_reg_2228;
wire   [10:0] select_ln318_12_fu_992_p3;
reg   [10:0] select_ln318_12_reg_2235;
wire   [0:0] or_ln318_5_fu_1097_p2;
reg   [0:0] or_ln318_5_reg_2241;
wire   [10:0] select_ln318_17_fu_1103_p3;
reg   [10:0] select_ln318_17_reg_2247;
wire   [8:0] select_ln318_18_fu_1111_p3;
reg   [8:0] select_ln318_18_reg_2257;
wire   [10:0] select_ln318_19_fu_1309_p3;
reg   [10:0] select_ln318_19_reg_2266;
wire   [10:0] select_ln318_20_fu_1317_p3;
reg   [10:0] select_ln318_20_reg_2272;
wire   [10:0] select_ln318_21_fu_1325_p3;
reg   [10:0] select_ln318_21_reg_2278;
wire   [8:0] select_ln318_22_fu_1332_p3;
reg   [8:0] select_ln318_22_reg_2288;
reg   [3:0] tmp_7_reg_2297;
wire   [10:0] mul_FL_V_7_fu_1359_p3;
reg   [10:0] mul_FL_V_7_reg_2302;
wire   [0:0] icmp_ln1496_1_fu_1367_p2;
reg   [0:0] icmp_ln1496_1_reg_2307;
wire   [10:0] p_neg_7_fu_1373_p3;
reg   [10:0] p_neg_7_reg_2313;
wire   [10:0] select_ln318_23_fu_1500_p3;
reg   [10:0] select_ln318_23_reg_2318;
wire   [10:0] select_ln318_25_fu_1514_p3;
reg   [10:0] select_ln318_25_reg_2324;
wire   [10:0] trunc_ln708_10_fu_1548_p4;
reg   [10:0] trunc_ln708_10_reg_2330;
wire   [10:0] p_neg_8_fu_1643_p3;
reg   [10:0] p_neg_8_reg_2335;
wire   [0:0] or_ln318_19_fu_1677_p2;
reg   [0:0] or_ln318_19_reg_2340;
wire   [10:0] select_ln318_28_fu_1683_p3;
reg   [10:0] select_ln318_28_reg_2346;
reg   [10:0] select_ln318_28_reg_2346_pp0_iter6_reg;
wire   [8:0] select_ln318_30_fu_1691_p3;
reg   [8:0] select_ln318_30_reg_2353;
wire   [10:0] select_ln318_27_fu_1717_p3;
reg   [10:0] select_ln318_27_reg_2362;
wire   [10:0] select_ln318_29_fu_1723_p3;
reg   [10:0] select_ln318_29_reg_2368;
wire   [10:0] mul_FL_V_9_fu_1758_p3;
reg   [10:0] mul_FL_V_9_reg_2373;
wire   [10:0] add_ln703_13_fu_1849_p2;
reg   [10:0] add_ln703_13_reg_2378;
wire   [0:0] or_ln318_22_fu_1879_p2;
reg   [0:0] or_ln318_22_reg_2383;
wire   [8:0] select_ln318_34_fu_1885_p3;
reg   [8:0] select_ln318_34_reg_2390;
wire    ap_block_pp0_stage0;
wire   [5:0] trunc_ln_fu_178_p4;
wire   [1:0] tmp_fu_196_p4;
wire   [2:0] zext_ln248_fu_206_p1;
wire   [8:0] x_l_I_V_fu_188_p1;
wire   [2:0] add_ln248_fu_216_p2;
wire   [0:0] icmp_ln488_fu_210_p2;
wire   [8:0] p_Result_s_26_fu_222_p5;
wire   [2:0] select_ln488_fu_234_p3;
wire   [1:0] p_Result_25_1_fu_250_p4;
wire   [8:0] select_ln488_1_fu_242_p3;
wire   [2:0] tmp_1_fu_260_p3;
wire   [3:0] p_Result_28_1_fu_268_p4;
wire   [3:0] zext_ln488_fu_278_p1;
wire   [3:0] sub_ln248_fu_288_p2;
wire   [0:0] icmp_ln488_1_fu_282_p2;
reg   [2:0] tmp_9_fu_306_p4;
wire   [8:0] p_Result_30_1_fu_294_p5;
wire   [8:0] select_ln488_3_fu_324_p3;
wire   [3:0] tmp_2_fu_332_p3;
wire   [4:0] trunc_ln612_fu_340_p1;
wire   [4:0] zext_ln488_1_fu_344_p1;
wire   [4:0] sub_ln248_1_fu_354_p2;
wire   [8:0] p_Result_30_2_fu_360_p5;
wire   [1:0] tmp_11_fu_380_p4;
wire   [1:0] tmp_16_fu_396_p4;
reg   [2:0] tmp_10_fu_419_p4;
wire   [6:0] trunc_ln708_1_fu_434_p3;
wire   [8:0] zext_ln1494_fu_442_p1;
wire   [10:0] x_l_FH_V_fu_412_p3;
wire   [8:0] add_ln703_fu_462_p2;
wire   [8:0] select_ln339_fu_467_p3;
wire   [0:0] icmp_ln1498_fu_451_p2;
wire   [0:0] and_ln318_fu_479_p2;
wire   [0:0] icmp_ln1494_fu_446_p2;
wire   [0:0] or_ln318_fu_484_p2;
wire   [10:0] add_ln703_15_fu_456_p2;
wire   [8:0] sub_ln703_fu_473_p2;
wire   [1:0] tmp_8_fu_523_p4;
wire   [0:0] trunc_ln708_fu_541_p1;
wire   [1:0] p_Result_34_1_fu_513_p4;
wire   [6:0] trunc_ln708_3_fu_533_p3;
wire   [8:0] zext_ln1494_1_fu_555_p1;
wire   [10:0] select_ln318_1_fu_498_p3;
wire   [10:0] trunc_ln708_4_fu_545_p4;
wire   [0:0] icmp_ln1495_1_fu_571_p2;
wire   [8:0] add_ln703_1_fu_583_p2;
wire   [8:0] select_ln339_1_fu_589_p3;
wire   [0:0] icmp_ln318_1_fu_603_p2;
wire   [0:0] icmp_ln1498_1_fu_565_p2;
wire   [0:0] xor_ln318_5_fu_609_p2;
wire   [0:0] and_ln318_1_fu_615_p2;
wire   [0:0] icmp_ln1494_1_fu_559_p2;
wire   [10:0] sub_ln703_1_fu_577_p2;
reg   [10:0] tmp_18_fu_647_p4;
wire   [10:0] select_ln318_3_fu_656_p3;
wire   [2:0] p_Result_34_2_fu_667_p4;
wire   [6:0] trunc_ln708_5_fu_677_p3;
wire   [8:0] select_ln318_5_fu_662_p3;
wire   [8:0] zext_ln1494_2_fu_693_p1;
wire   [10:0] trunc_ln708_6_fu_684_p4;
wire   [0:0] icmp_ln1495_2_fu_709_p2;
wire   [8:0] add_ln703_2_fu_719_p2;
wire   [8:0] select_ln339_2_fu_725_p3;
wire   [0:0] icmp_ln318_2_fu_749_p2;
wire   [0:0] icmp_ln1498_2_fu_703_p2;
wire   [0:0] xor_ln318_6_fu_754_p2;
wire   [0:0] and_ln318_2_fu_760_p2;
wire   [0:0] icmp_ln1494_2_fu_697_p2;
wire   [0:0] or_ln318_2_fu_766_p2;
reg   [10:0] tmp_20_fu_739_p4;
wire   [10:0] sub_ln703_3_fu_714_p2;
wire   [8:0] sub_ln703_4_fu_733_p2;
wire   [3:0] p_Result_34_3_fu_795_p4;
wire   [10:0] trunc_ln708_8_fu_805_p4;
wire   [0:0] icmp_ln318_3_fu_844_p2;
wire   [0:0] icmp_ln1498_3_fu_820_p2;
wire   [0:0] xor_ln318_7_fu_850_p2;
wire   [0:0] and_ln318_3_fu_856_p2;
wire   [0:0] icmp_ln1494_3_fu_814_p2;
reg   [10:0] tmp_21_fu_873_p4;
wire   [8:0] select_ln339_3_fu_868_p3;
wire   [10:0] select_ln318_9_fu_882_p3;
wire   [4:0] p_Result_34_4_fu_899_p4;
wire   [8:0] select_ln318_11_fu_893_p3;
wire   [10:0] select_ln318_10_fu_888_p3;
wire   [10:0] trunc_ln708_s_fu_909_p5;
wire   [0:0] icmp_ln1495_4_fu_932_p2;
wire   [8:0] add_ln703_4_fu_944_p2;
wire   [0:0] icmp_ln318_4_fu_968_p2;
wire   [0:0] icmp_ln1498_4_fu_926_p2;
wire   [0:0] xor_ln318_8_fu_974_p2;
wire   [0:0] and_ln318_4_fu_980_p2;
wire   [0:0] icmp_ln1494_4_fu_920_p2;
wire   [0:0] or_ln318_4_fu_986_p2;
reg   [10:0] tmp_22_fu_958_p4;
wire   [10:0] sub_ln703_6_fu_938_p2;
wire   [8:0] select_ln339_4_fu_950_p3;
wire   [5:0] p_Result_34_5_fu_1016_p4;
wire   [8:0] select_ln318_14_fu_1008_p3;
wire   [10:0] select_ln318_13_fu_1000_p3;
wire   [10:0] trunc_ln708_2_fu_1026_p4;
wire   [0:0] icmp_ln1498_5_fu_1041_p2;
wire   [0:0] icmp_ln1494_11_fu_1047_p2;
wire   [0:0] icmp_ln331_fu_1059_p2;
wire   [10:0] xor_ln703_fu_1071_p2;
wire   [0:0] xor_ln331_fu_1065_p2;
wire   [8:0] add_ln703_6_fu_1083_p2;
wire   [0:0] icmp_ln1494_5_fu_1035_p2;
wire   [0:0] and_ln318_5_fu_1053_p2;
wire   [10:0] add_ln703_5_fu_1077_p2;
wire   [8:0] select_ln339_5_fu_1089_p3;
reg   [10:0] tmp_23_fu_1119_p4;
wire   [10:0] select_ln318_15_fu_1128_p3;
wire   [4:0] tmp_s_fu_1151_p4;
wire   [1:0] tmp_3_fu_1141_p4;
wire   [10:0] trunc_ln708_7_fu_1161_p4;
wire   [0:0] icmp_ln1498_6_fu_1183_p2;
wire   [0:0] icmp_ln1494_12_fu_1188_p2;
wire   [10:0] select_ln318_16_fu_1134_p3;
wire   [10:0] mul_FL_V_6_fu_1170_p3;
wire   [0:0] icmp_ln1494_6_fu_1178_p2;
wire   [0:0] icmp_ln1496_fu_1204_p2;
wire   [0:0] or_ln318_7_fu_1210_p2;
wire   [0:0] icmp_ln318_5_fu_1199_p2;
wire   [0:0] icmp_ln1498_11_fu_1233_p2;
wire   [0:0] icmp_ln1495_5_fu_1228_p2;
wire   [0:0] and_ln331_fu_1238_p2;
wire   [10:0] p_neg_6_fu_1250_p3;
wire   [10:0] sub_ln703_8_fu_1258_p2;
wire   [0:0] or_ln331_fu_1244_p2;
wire   [8:0] add_ln703_8_fu_1269_p2;
wire   [0:0] or_ln318_6_fu_1216_p2;
wire   [0:0] and_ln318_6_fu_1193_p2;
wire   [0:0] xor_ln318_fu_1291_p2;
wire   [0:0] or_ln318_8_fu_1297_p2;
wire   [0:0] or_ln318_9_fu_1303_p2;
reg   [10:0] tmp_24_fu_1281_p4;
wire   [10:0] sub_ln703_7_fu_1222_p2;
wire   [10:0] add_ln703_7_fu_1264_p2;
wire   [8:0] select_ln339_6_fu_1274_p3;
wire   [3:0] tmp_4_fu_1339_p4;
wire   [10:0] trunc_ln708_9_fu_1381_p4;
wire   [0:0] icmp_ln1498_7_fu_1394_p2;
wire   [0:0] icmp_ln1494_13_fu_1399_p2;
wire   [0:0] icmp_ln1494_7_fu_1389_p2;
wire   [0:0] or_ln318_10_fu_1415_p2;
wire   [0:0] icmp_ln318_6_fu_1410_p2;
wire   [0:0] icmp_ln1498_12_fu_1435_p2;
wire   [0:0] icmp_ln1495_6_fu_1430_p2;
wire   [0:0] and_ln331_1_fu_1440_p2;
wire   [10:0] sub_ln703_10_fu_1451_p2;
wire   [0:0] or_ln331_1_fu_1445_p2;
wire   [8:0] add_ln703_10_fu_1461_p2;
wire   [0:0] or_ln318_11_fu_1420_p2;
wire   [0:0] and_ln318_7_fu_1404_p2;
wire   [0:0] xor_ln318_1_fu_1482_p2;
wire   [0:0] or_ln318_15_fu_1488_p2;
wire   [0:0] or_ln318_16_fu_1494_p2;
reg   [10:0] tmp_25_fu_1473_p4;
wire   [10:0] sub_ln703_9_fu_1426_p2;
wire   [10:0] add_ln703_9_fu_1456_p2;
wire   [8:0] select_ln339_7_fu_1466_p3;
wire   [2:0] tmp_12_fu_1538_p4;
wire   [5:0] tmp_5_fu_1528_p4;
wire   [8:0] select_ln318_26_fu_1521_p3;
wire   [0:0] icmp_ln1498_8_fu_1571_p2;
wire   [0:0] icmp_ln1494_14_fu_1577_p2;
wire   [10:0] select_ln318_24_fu_1507_p3;
wire   [10:0] mul_FL_V_8_fu_1557_p3;
wire   [0:0] icmp_ln1494_8_fu_1565_p2;
wire   [0:0] icmp_ln1496_2_fu_1595_p2;
wire   [0:0] or_ln318_17_fu_1601_p2;
wire   [0:0] icmp_ln318_7_fu_1589_p2;
wire   [0:0] icmp_ln1498_13_fu_1625_p2;
wire   [0:0] icmp_ln1495_7_fu_1619_p2;
wire   [0:0] and_ln331_2_fu_1631_p2;
wire   [0:0] or_ln331_2_fu_1637_p2;
wire   [8:0] add_ln703_12_fu_1651_p2;
wire   [0:0] or_ln318_12_fu_1607_p2;
wire   [0:0] and_ln318_8_fu_1583_p2;
wire   [0:0] xor_ln318_2_fu_1665_p2;
wire   [0:0] or_ln318_18_fu_1671_p2;
wire   [10:0] sub_ln703_11_fu_1613_p2;
wire   [8:0] select_ln339_8_fu_1657_p3;
wire   [10:0] sub_ln703_12_fu_1699_p2;
reg   [10:0] tmp_26_fu_1708_p4;
wire   [10:0] add_ln703_11_fu_1703_p2;
wire   [1:0] tmp_13_fu_1739_p4;
wire   [7:0] tmp_6_fu_1729_p4;
wire   [10:0] trunc_ln708_11_fu_1749_p4;
wire   [0:0] icmp_ln1498_9_fu_1771_p2;
wire   [0:0] icmp_ln1494_15_fu_1776_p2;
wire   [0:0] icmp_ln1494_9_fu_1766_p2;
wire   [0:0] icmp_ln1496_3_fu_1794_p2;
wire   [0:0] or_ln318_20_fu_1799_p2;
wire   [0:0] icmp_ln318_8_fu_1788_p2;
wire   [0:0] icmp_ln1498_14_fu_1817_p2;
wire   [0:0] icmp_ln1495_8_fu_1811_p2;
wire   [0:0] and_ln331_3_fu_1823_p2;
wire   [10:0] p_neg_9_fu_1835_p3;
wire   [10:0] sub_ln703_14_fu_1843_p2;
wire   [0:0] or_ln331_3_fu_1829_p2;
wire   [8:0] add_ln703_14_fu_1855_p2;
wire   [0:0] or_ln318_13_fu_1805_p2;
wire   [0:0] and_ln318_9_fu_1782_p2;
wire   [0:0] xor_ln318_3_fu_1867_p2;
wire   [0:0] or_ln318_21_fu_1873_p2;
wire   [8:0] select_ln339_9_fu_1860_p3;
reg   [10:0] tmp_27_fu_1903_p4;
wire   [10:0] sub_ln703_13_fu_1899_p2;
wire   [10:0] select_ln318_31_fu_1912_p3;
wire   [9:0] trunc_ln103_fu_1929_p1;
wire   [0:0] tmp_28_fu_1941_p3;
wire   [10:0] select_ln318_33_fu_1924_p3;
wire   [10:0] trunc_ln708_12_fu_1949_p4;
wire   [0:0] icmp_ln1498_10_fu_1963_p2;
wire   [0:0] icmp_ln1494_16_fu_1968_p2;
wire   [10:0] select_ln318_32_fu_1918_p3;
wire   [10:0] mul_FL_V_s_fu_1933_p3;
wire   [0:0] icmp_ln1494_10_fu_1958_p2;
wire   [0:0] icmp_ln1496_4_fu_1986_p2;
wire   [0:0] or_ln318_23_fu_1992_p2;
wire   [0:0] icmp_ln318_9_fu_1980_p2;
wire   [0:0] or_ln318_14_fu_1998_p2;
wire   [0:0] and_ln318_10_fu_1974_p2;
wire   [0:0] xor_ln318_4_fu_2014_p2;
wire   [0:0] or_ln318_24_fu_2020_p2;
wire   [0:0] or_ln318_25_fu_2026_p2;
reg   [10:0] tmp_29_fu_2004_p4;
wire   [10:0] select_ln318_35_fu_2032_p3;
wire   [11:0] zext_ln1192_fu_2040_p1;
wire   [11:0] res_FH_l_V_fu_2044_p2;
wire   [0:0] p_Result_1_fu_2056_p3;
wire   [2:0] res_I_V_fu_2064_p2;
wire   [10:0] res_FH_V_fu_2050_p2;
wire   [2:0] p_Val2_s_fu_2069_p3;
wire   [9:0] tmp_14_fu_2076_p4;
wire   [0:0] p_Result_s_fu_1892_p3;
wire   [12:0] r_V_fu_2086_p3;
reg   [15:0] x_V_int_reg;

always @ (posedge ap_clk) begin
    x_V_int_reg <= x_V;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln703_13_reg_2378 <= add_ln703_13_fu_1849_p2;
        add_ln703_3_reg_2223 <= add_ln703_3_fu_838_p2;
        icmp_ln1495_3_reg_2213 <= icmp_ln1495_3_fu_826_p2;
        icmp_ln1495_reg_2132 <= icmp_ln1495_fu_390_p2;
        icmp_ln1496_1_reg_2307 <= icmp_ln1496_1_fu_1367_p2;
        icmp_ln318_reg_2137 <= icmp_ln318_fu_406_p2;
        icmp_ln488_2_reg_2118 <= icmp_ln488_2_fu_348_p2;
        mul_FL_V_7_reg_2302[10 : 7] <= mul_FL_V_7_fu_1359_p3[10 : 7];
        mul_FL_V_9_reg_2373[10 : 3] <= mul_FL_V_9_fu_1758_p3[10 : 3];
        or_ln318_19_reg_2340 <= or_ln318_19_fu_1677_p2;
        or_ln318_1_reg_2172 <= or_ln318_1_fu_621_p2;
        or_ln318_22_reg_2383 <= or_ln318_22_fu_1879_p2;
        or_ln318_3_reg_2228 <= or_ln318_3_fu_862_p2;
        or_ln318_5_reg_2241 <= or_ln318_5_fu_1097_p2;
        p_neg_7_reg_2313 <= p_neg_7_fu_1373_p3;
        p_neg_8_reg_2335 <= p_neg_8_fu_1643_p3;
        select_ln318_12_reg_2235 <= select_ln318_12_fu_992_p3;
        select_ln318_17_reg_2247 <= select_ln318_17_fu_1103_p3;
        select_ln318_18_reg_2257 <= select_ln318_18_fu_1111_p3;
        select_ln318_19_reg_2266 <= select_ln318_19_fu_1309_p3;
        select_ln318_20_reg_2272[10 : 8] <= select_ln318_20_fu_1317_p3[10 : 8];
        select_ln318_21_reg_2278 <= select_ln318_21_fu_1325_p3;
        select_ln318_22_reg_2288 <= select_ln318_22_fu_1332_p3;
        select_ln318_23_reg_2318 <= select_ln318_23_fu_1500_p3;
        select_ln318_25_reg_2324 <= select_ln318_25_fu_1514_p3;
        select_ln318_27_reg_2362 <= select_ln318_27_fu_1717_p3;
        select_ln318_28_reg_2346[10 : 4] <= select_ln318_28_fu_1683_p3[10 : 4];
        select_ln318_28_reg_2346_pp0_iter6_reg[10 : 4] <= select_ln318_28_reg_2346[10 : 4];
        select_ln318_29_reg_2368 <= select_ln318_29_fu_1723_p3;
        select_ln318_2_reg_2162 <= select_ln318_2_fu_506_p3;
        select_ln318_30_reg_2353 <= select_ln318_30_fu_1691_p3;
        select_ln318_34_reg_2390 <= select_ln318_34_fu_1885_p3;
        select_ln318_4_reg_2178[10 : 1] <= select_ln318_4_fu_627_p3[10 : 1];
        select_ln318_6_reg_2196 <= select_ln318_6_fu_772_p3;
        select_ln318_7_reg_2202[10 : 1] <= select_ln318_7_fu_780_p3[10 : 1];
        select_ln318_8_reg_2207 <= select_ln318_8_fu_787_p3;
        select_ln318_reg_2156[10] <= select_ln318_fu_490_p3[10];
        select_ln488_2_reg_2112 <= select_ln488_2_fu_316_p3;
        select_ln488_4_reg_2142 <= select_ln488_4_fu_428_p3;
        select_ln488_4_reg_2142_pp0_iter2_reg <= select_ln488_4_reg_2142;
        select_ln488_4_reg_2142_pp0_iter3_reg <= select_ln488_4_reg_2142_pp0_iter2_reg;
        select_ln488_4_reg_2142_pp0_iter4_reg <= select_ln488_4_reg_2142_pp0_iter3_reg;
        select_ln488_4_reg_2142_pp0_iter5_reg <= select_ln488_4_reg_2142_pp0_iter4_reg;
        select_ln488_4_reg_2142_pp0_iter6_reg <= select_ln488_4_reg_2142_pp0_iter5_reg;
        select_ln488_5_reg_2123 <= select_ln488_5_fu_372_p3;
        sub_ln703_2_reg_2167 <= sub_ln703_2_fu_597_p2;
        sub_ln703_5_reg_2218[10 : 1] <= sub_ln703_5_fu_832_p2[10 : 1];
        tmp_19_reg_2186 <= select_ln488_4_fu_428_p3[32'd2];
        tmp_7_reg_2297 <= {{select_ln318_19_fu_1309_p3[10:7]}};
        trunc_ln708_10_reg_2330[5 : 0] <= trunc_ln708_10_fu_1548_p4[5 : 0];
        trunc_ln708_13_reg_2191 <= trunc_ln708_13_fu_643_p1;
        trunc_ln731_reg_2107 <= trunc_ln731_fu_192_p1;
        x_V_read_reg_2102 <= x_V_int_reg;
        x_V_read_reg_2102_pp0_iter1_reg <= x_V_read_reg_2102;
        x_V_read_reg_2102_pp0_iter2_reg <= x_V_read_reg_2102_pp0_iter1_reg;
        x_V_read_reg_2102_pp0_iter3_reg <= x_V_read_reg_2102_pp0_iter2_reg;
        x_V_read_reg_2102_pp0_iter4_reg <= x_V_read_reg_2102_pp0_iter3_reg;
        x_V_read_reg_2102_pp0_iter5_reg <= x_V_read_reg_2102_pp0_iter4_reg;
        x_V_read_reg_2102_pp0_iter6_reg <= x_V_read_reg_2102_pp0_iter5_reg;
    end
end

assign add_ln248_fu_216_p2 = ($signed(zext_ln248_fu_206_p1) + $signed(3'd7));

assign add_ln703_10_fu_1461_p2 = ($signed(select_ln318_22_reg_2288) + $signed(9'd511));

assign add_ln703_11_fu_1703_p2 = (sub_ln703_12_fu_1699_p2 + select_ln318_25_reg_2324);

assign add_ln703_12_fu_1651_p2 = ($signed(select_ln318_26_fu_1521_p3) + $signed(9'd511));

assign add_ln703_13_fu_1849_p2 = (sub_ln703_14_fu_1843_p2 + select_ln318_29_fu_1723_p3);

assign add_ln703_14_fu_1855_p2 = ($signed(select_ln318_30_reg_2353) + $signed(9'd511));

assign add_ln703_15_fu_456_p2 = ($signed(x_l_FH_V_fu_412_p3) + $signed(11'd1536));

assign add_ln703_1_fu_583_p2 = ($signed(select_ln318_2_fu_506_p3) + $signed(9'd511));

assign add_ln703_2_fu_719_p2 = ($signed(select_ln318_5_fu_662_p3) + $signed(9'd511));

assign add_ln703_3_fu_838_p2 = ($signed(select_ln318_8_fu_787_p3) + $signed(9'd511));

assign add_ln703_4_fu_944_p2 = ($signed(select_ln318_11_fu_893_p3) + $signed(9'd511));

assign add_ln703_5_fu_1077_p2 = (select_ln318_13_fu_1000_p3 + xor_ln703_fu_1071_p2);

assign add_ln703_6_fu_1083_p2 = ($signed(select_ln318_14_fu_1008_p3) + $signed(9'd511));

assign add_ln703_7_fu_1264_p2 = (sub_ln703_8_fu_1258_p2 + select_ln318_17_reg_2247);

assign add_ln703_8_fu_1269_p2 = ($signed(select_ln318_18_reg_2257) + $signed(9'd511));

assign add_ln703_9_fu_1456_p2 = (sub_ln703_10_fu_1451_p2 + select_ln318_21_reg_2278);

assign add_ln703_fu_462_p2 = ($signed(select_ln488_5_reg_2123) + $signed(9'd511));

assign and_ln318_10_fu_1974_p2 = (icmp_ln1498_10_fu_1963_p2 & icmp_ln1494_16_fu_1968_p2);

assign and_ln318_1_fu_615_p2 = (xor_ln318_5_fu_609_p2 & icmp_ln1498_1_fu_565_p2);

assign and_ln318_2_fu_760_p2 = (xor_ln318_6_fu_754_p2 & icmp_ln1498_2_fu_703_p2);

assign and_ln318_3_fu_856_p2 = (xor_ln318_7_fu_850_p2 & icmp_ln1498_3_fu_820_p2);

assign and_ln318_4_fu_980_p2 = (xor_ln318_8_fu_974_p2 & icmp_ln1498_4_fu_926_p2);

assign and_ln318_5_fu_1053_p2 = (icmp_ln1498_5_fu_1041_p2 & icmp_ln1494_11_fu_1047_p2);

assign and_ln318_6_fu_1193_p2 = (icmp_ln1498_6_fu_1183_p2 & icmp_ln1494_12_fu_1188_p2);

assign and_ln318_7_fu_1404_p2 = (icmp_ln1498_7_fu_1394_p2 & icmp_ln1494_13_fu_1399_p2);

assign and_ln318_8_fu_1583_p2 = (icmp_ln1498_8_fu_1571_p2 & icmp_ln1494_14_fu_1577_p2);

assign and_ln318_9_fu_1782_p2 = (icmp_ln1498_9_fu_1771_p2 & icmp_ln1494_15_fu_1776_p2);

assign and_ln318_fu_479_p2 = (icmp_ln318_reg_2137 & icmp_ln1498_fu_451_p2);

assign and_ln331_1_fu_1440_p2 = (icmp_ln1498_12_fu_1435_p2 & icmp_ln1496_1_reg_2307);

assign and_ln331_2_fu_1631_p2 = (icmp_ln1498_13_fu_1625_p2 & icmp_ln1496_2_fu_1595_p2);

assign and_ln331_3_fu_1823_p2 = (icmp_ln1498_14_fu_1817_p2 & icmp_ln1496_3_fu_1794_p2);

assign and_ln331_fu_1238_p2 = (icmp_ln1498_11_fu_1233_p2 & icmp_ln1496_fu_1204_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_return = ((p_Result_s_fu_1892_p3[0:0] === 1'b1) ? 13'd0 : r_V_fu_2086_p3);

assign icmp_ln1494_10_fu_1958_p2 = ((select_ln318_34_reg_2390 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_11_fu_1047_p2 = ((select_ln318_13_fu_1000_p3 > trunc_ln708_2_fu_1026_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_12_fu_1188_p2 = ((select_ln318_17_reg_2247 > trunc_ln708_7_fu_1161_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_13_fu_1399_p2 = ((select_ln318_21_reg_2278 > trunc_ln708_9_fu_1381_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_14_fu_1577_p2 = ((select_ln318_25_fu_1514_p3 > trunc_ln708_10_fu_1548_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_15_fu_1776_p2 = ((select_ln318_29_fu_1723_p3 > trunc_ln708_11_fu_1749_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_16_fu_1968_p2 = ((select_ln318_33_fu_1924_p3 > trunc_ln708_12_fu_1949_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_1_fu_559_p2 = ((select_ln318_2_fu_506_p3 > zext_ln1494_1_fu_555_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_2_fu_697_p2 = ((select_ln318_5_fu_662_p3 > zext_ln1494_2_fu_693_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_3_fu_814_p2 = ((select_ln318_8_fu_787_p3 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_4_fu_920_p2 = ((select_ln318_11_fu_893_p3 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_5_fu_1035_p2 = ((select_ln318_14_fu_1008_p3 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_6_fu_1178_p2 = ((select_ln318_18_reg_2257 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_7_fu_1389_p2 = ((select_ln318_22_reg_2288 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_8_fu_1565_p2 = ((select_ln318_26_fu_1521_p3 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_9_fu_1766_p2 = ((select_ln318_30_reg_2353 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_446_p2 = ((select_ln488_5_reg_2123 > zext_ln1494_fu_442_p1) ? 1'b1 : 1'b0);

assign icmp_ln1495_1_fu_571_p2 = ((select_ln318_1_fu_498_p3 < trunc_ln708_4_fu_545_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_2_fu_709_p2 = ((select_ln318_4_reg_2178 < trunc_ln708_6_fu_684_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_3_fu_826_p2 = ((select_ln318_7_fu_780_p3 < trunc_ln708_8_fu_805_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_4_fu_932_p2 = ((select_ln318_10_fu_888_p3 < trunc_ln708_s_fu_909_p5) ? 1'b1 : 1'b0);

assign icmp_ln1495_5_fu_1228_p2 = ((select_ln318_17_reg_2247 < trunc_ln708_7_fu_1161_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_6_fu_1430_p2 = ((select_ln318_21_reg_2278 < trunc_ln708_9_fu_1381_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_7_fu_1619_p2 = ((select_ln318_25_fu_1514_p3 < trunc_ln708_10_fu_1548_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_8_fu_1811_p2 = ((select_ln318_29_fu_1723_p3 < trunc_ln708_11_fu_1749_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_fu_390_p2 = ((tmp_11_fu_380_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1496_1_fu_1367_p2 = ((select_ln318_20_fu_1317_p3 < mul_FL_V_7_fu_1359_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_2_fu_1595_p2 = ((select_ln318_24_fu_1507_p3 < mul_FL_V_8_fu_1557_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_3_fu_1794_p2 = ((select_ln318_28_reg_2346 < mul_FL_V_9_fu_1758_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_4_fu_1986_p2 = ((select_ln318_32_fu_1918_p3 < mul_FL_V_s_fu_1933_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_fu_1204_p2 = ((select_ln318_16_fu_1134_p3 < mul_FL_V_6_fu_1170_p3) ? 1'b1 : 1'b0);

assign icmp_ln1498_10_fu_1963_p2 = ((select_ln318_34_reg_2390 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_11_fu_1233_p2 = ((select_ln318_17_reg_2247 == trunc_ln708_7_fu_1161_p4) ? 1'b1 : 1'b0);

assign icmp_ln1498_12_fu_1435_p2 = ((select_ln318_21_reg_2278 == trunc_ln708_9_fu_1381_p4) ? 1'b1 : 1'b0);

assign icmp_ln1498_13_fu_1625_p2 = ((select_ln318_25_fu_1514_p3 == trunc_ln708_10_fu_1548_p4) ? 1'b1 : 1'b0);

assign icmp_ln1498_14_fu_1817_p2 = ((select_ln318_29_fu_1723_p3 == trunc_ln708_11_fu_1749_p4) ? 1'b1 : 1'b0);

assign icmp_ln1498_1_fu_565_p2 = ((select_ln318_2_fu_506_p3 == zext_ln1494_1_fu_555_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_2_fu_703_p2 = ((select_ln318_5_fu_662_p3 == zext_ln1494_2_fu_693_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_3_fu_820_p2 = ((select_ln318_8_fu_787_p3 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_4_fu_926_p2 = ((select_ln318_11_fu_893_p3 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_5_fu_1041_p2 = ((select_ln318_14_fu_1008_p3 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_6_fu_1183_p2 = ((select_ln318_18_reg_2257 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_7_fu_1394_p2 = ((select_ln318_22_reg_2288 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_8_fu_1571_p2 = ((select_ln318_26_fu_1521_p3 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_9_fu_1771_p2 = ((select_ln318_30_reg_2353 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_fu_451_p2 = ((select_ln488_5_reg_2123 == zext_ln1494_fu_442_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_1_fu_603_p2 = ((select_ln318_1_fu_498_p3 < trunc_ln708_4_fu_545_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_2_fu_749_p2 = ((select_ln318_4_reg_2178 < trunc_ln708_6_fu_684_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_3_fu_844_p2 = ((select_ln318_7_fu_780_p3 < trunc_ln708_8_fu_805_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_4_fu_968_p2 = ((select_ln318_10_fu_888_p3 < trunc_ln708_s_fu_909_p5) ? 1'b1 : 1'b0);

assign icmp_ln318_5_fu_1199_p2 = ((select_ln318_17_reg_2247 != trunc_ln708_7_fu_1161_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_6_fu_1410_p2 = ((select_ln318_21_reg_2278 != trunc_ln708_9_fu_1381_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_7_fu_1589_p2 = ((select_ln318_25_fu_1514_p3 != trunc_ln708_10_fu_1548_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_8_fu_1788_p2 = ((select_ln318_29_fu_1723_p3 != trunc_ln708_11_fu_1749_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_9_fu_1980_p2 = ((select_ln318_33_fu_1924_p3 != trunc_ln708_12_fu_1949_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_fu_406_p2 = ((tmp_16_fu_396_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln331_fu_1059_p2 = ((trunc_ln708_2_fu_1026_p4 < select_ln318_13_fu_1000_p3) ? 1'b1 : 1'b0);

assign icmp_ln488_1_fu_282_p2 = ((p_Result_28_1_fu_268_p4 < zext_ln488_fu_278_p1) ? 1'b1 : 1'b0);

assign icmp_ln488_2_fu_348_p2 = ((trunc_ln612_fu_340_p1 < zext_ln488_1_fu_344_p1) ? 1'b1 : 1'b0);

assign icmp_ln488_fu_210_p2 = ((tmp_fu_196_p4 == 2'd0) ? 1'b1 : 1'b0);

assign mul_FL_V_6_fu_1170_p3 = {{tmp_3_fu_1141_p4}, {9'd256}};

assign mul_FL_V_7_fu_1359_p3 = {{tmp_4_fu_1339_p4}, {7'd64}};

assign mul_FL_V_8_fu_1557_p3 = {{tmp_5_fu_1528_p4}, {5'd16}};

assign mul_FL_V_9_fu_1758_p3 = {{tmp_6_fu_1729_p4}, {3'd4}};

assign mul_FL_V_s_fu_1933_p3 = {{trunc_ln103_fu_1929_p1}, {1'd1}};

assign or_ln318_10_fu_1415_p2 = (icmp_ln1496_1_reg_2307 | icmp_ln1494_7_fu_1389_p2);

assign or_ln318_11_fu_1420_p2 = (or_ln318_10_fu_1415_p2 | icmp_ln318_6_fu_1410_p2);

assign or_ln318_12_fu_1607_p2 = (or_ln318_17_fu_1601_p2 | icmp_ln318_7_fu_1589_p2);

assign or_ln318_13_fu_1805_p2 = (or_ln318_20_fu_1799_p2 | icmp_ln318_8_fu_1788_p2);

assign or_ln318_14_fu_1998_p2 = (or_ln318_23_fu_1992_p2 | icmp_ln318_9_fu_1980_p2);

assign or_ln318_15_fu_1488_p2 = (xor_ln318_1_fu_1482_p2 | and_ln318_7_fu_1404_p2);

assign or_ln318_16_fu_1494_p2 = (or_ln318_15_fu_1488_p2 | icmp_ln1494_7_fu_1389_p2);

assign or_ln318_17_fu_1601_p2 = (icmp_ln1496_2_fu_1595_p2 | icmp_ln1494_8_fu_1565_p2);

assign or_ln318_18_fu_1671_p2 = (xor_ln318_2_fu_1665_p2 | and_ln318_8_fu_1583_p2);

assign or_ln318_19_fu_1677_p2 = (or_ln318_18_fu_1671_p2 | icmp_ln1494_8_fu_1565_p2);

assign or_ln318_1_fu_621_p2 = (icmp_ln1494_1_fu_559_p2 | and_ln318_1_fu_615_p2);

assign or_ln318_20_fu_1799_p2 = (icmp_ln1496_3_fu_1794_p2 | icmp_ln1494_9_fu_1766_p2);

assign or_ln318_21_fu_1873_p2 = (xor_ln318_3_fu_1867_p2 | and_ln318_9_fu_1782_p2);

assign or_ln318_22_fu_1879_p2 = (or_ln318_21_fu_1873_p2 | icmp_ln1494_9_fu_1766_p2);

assign or_ln318_23_fu_1992_p2 = (icmp_ln1496_4_fu_1986_p2 | icmp_ln1494_10_fu_1958_p2);

assign or_ln318_24_fu_2020_p2 = (xor_ln318_4_fu_2014_p2 | and_ln318_10_fu_1974_p2);

assign or_ln318_25_fu_2026_p2 = (or_ln318_24_fu_2020_p2 | icmp_ln1494_10_fu_1958_p2);

assign or_ln318_2_fu_766_p2 = (icmp_ln1494_2_fu_697_p2 | and_ln318_2_fu_760_p2);

assign or_ln318_3_fu_862_p2 = (icmp_ln1494_3_fu_814_p2 | and_ln318_3_fu_856_p2);

assign or_ln318_4_fu_986_p2 = (icmp_ln1494_4_fu_920_p2 | and_ln318_4_fu_980_p2);

assign or_ln318_5_fu_1097_p2 = (icmp_ln1494_5_fu_1035_p2 | and_ln318_5_fu_1053_p2);

assign or_ln318_6_fu_1216_p2 = (or_ln318_7_fu_1210_p2 | icmp_ln318_5_fu_1199_p2);

assign or_ln318_7_fu_1210_p2 = (icmp_ln1496_fu_1204_p2 | icmp_ln1494_6_fu_1178_p2);

assign or_ln318_8_fu_1297_p2 = (xor_ln318_fu_1291_p2 | and_ln318_6_fu_1193_p2);

assign or_ln318_9_fu_1303_p2 = (or_ln318_8_fu_1297_p2 | icmp_ln1494_6_fu_1178_p2);

assign or_ln318_fu_484_p2 = (icmp_ln1494_fu_446_p2 | and_ln318_fu_479_p2);

assign or_ln331_1_fu_1445_p2 = (icmp_ln1495_6_fu_1430_p2 | and_ln331_1_fu_1440_p2);

assign or_ln331_2_fu_1637_p2 = (icmp_ln1495_7_fu_1619_p2 | and_ln331_2_fu_1631_p2);

assign or_ln331_3_fu_1829_p2 = (icmp_ln1495_8_fu_1811_p2 | and_ln331_3_fu_1823_p2);

assign or_ln331_fu_1244_p2 = (icmp_ln1495_5_fu_1228_p2 | and_ln331_fu_1238_p2);

assign p_Result_1_fu_2056_p3 = res_FH_l_V_fu_2044_p2[32'd11];

assign p_Result_25_1_fu_250_p4 = {{select_ln488_fu_234_p3[2:1]}};

assign p_Result_28_1_fu_268_p4 = {{select_ln488_1_fu_242_p3[5:2]}};

assign p_Result_30_1_fu_294_p5 = {{select_ln488_1_fu_242_p3[8:6]}, {sub_ln248_fu_288_p2}, {select_ln488_1_fu_242_p3[1:0]}};

assign p_Result_30_2_fu_360_p5 = {{select_ln488_3_fu_324_p3[8:5]}, {sub_ln248_1_fu_354_p2}};

assign p_Result_34_1_fu_513_p4 = {{select_ln318_fu_490_p3[10:9]}};

assign p_Result_34_2_fu_667_p4 = {{select_ln318_3_fu_656_p3[10:8]}};

assign p_Result_34_3_fu_795_p4 = {{select_ln318_6_fu_772_p3[10:7]}};

assign p_Result_34_4_fu_899_p4 = {{select_ln318_9_fu_882_p3[10:6]}};

assign p_Result_34_5_fu_1016_p4 = {{select_ln318_12_fu_992_p3[10:5]}};

assign p_Result_s_26_fu_222_p5 = {{x_l_I_V_fu_188_p1[8:7]}, {add_ln248_fu_216_p2}, {x_l_I_V_fu_188_p1[3:0]}};

assign p_Result_s_fu_1892_p3 = x_V_read_reg_2102_pp0_iter6_reg[32'd15];

assign p_Val2_s_fu_2069_p3 = ((p_Result_1_fu_2056_p3[0:0] === 1'b1) ? res_I_V_fu_2064_p2 : select_ln488_4_reg_2142_pp0_iter6_reg);

assign p_neg_6_fu_1250_p3 = ((icmp_ln1496_fu_1204_p2[0:0] === 1'b1) ? 11'd2047 : 11'd0);

assign p_neg_7_fu_1373_p3 = ((icmp_ln1496_1_fu_1367_p2[0:0] === 1'b1) ? 11'd2047 : 11'd0);

assign p_neg_8_fu_1643_p3 = ((icmp_ln1496_2_fu_1595_p2[0:0] === 1'b1) ? 11'd2047 : 11'd0);

assign p_neg_9_fu_1835_p3 = ((icmp_ln1496_3_fu_1794_p2[0:0] === 1'b1) ? 11'd2047 : 11'd0);

assign r_V_fu_2086_p3 = {{p_Val2_s_fu_2069_p3}, {tmp_14_fu_2076_p4}};

assign res_FH_V_fu_2050_p2 = (select_ln318_35_fu_2032_p3 + 11'd1);

assign res_FH_l_V_fu_2044_p2 = (zext_ln1192_fu_2040_p1 + 12'd1);

assign res_I_V_fu_2064_p2 = (select_ln488_4_reg_2142_pp0_iter6_reg + 3'd1);

assign select_ln318_10_fu_888_p3 = ((or_ln318_3_reg_2228[0:0] === 1'b1) ? sub_ln703_5_reg_2218 : select_ln318_7_reg_2202);

assign select_ln318_11_fu_893_p3 = ((or_ln318_3_reg_2228[0:0] === 1'b1) ? select_ln339_3_fu_868_p3 : select_ln318_8_reg_2207);

assign select_ln318_12_fu_992_p3 = ((or_ln318_4_fu_986_p2[0:0] === 1'b1) ? tmp_22_fu_958_p4 : select_ln318_9_fu_882_p3);

assign select_ln318_13_fu_1000_p3 = ((or_ln318_4_fu_986_p2[0:0] === 1'b1) ? sub_ln703_6_fu_938_p2 : select_ln318_10_fu_888_p3);

assign select_ln318_14_fu_1008_p3 = ((or_ln318_4_fu_986_p2[0:0] === 1'b1) ? select_ln339_4_fu_950_p3 : select_ln318_11_fu_893_p3);

assign select_ln318_15_fu_1128_p3 = ((or_ln318_5_reg_2241[0:0] === 1'b1) ? tmp_23_fu_1119_p4 : select_ln318_12_reg_2235);

assign select_ln318_16_fu_1134_p3 = ((or_ln318_5_reg_2241[0:0] === 1'b1) ? 11'd1024 : 11'd0);

assign select_ln318_17_fu_1103_p3 = ((or_ln318_5_fu_1097_p2[0:0] === 1'b1) ? add_ln703_5_fu_1077_p2 : select_ln318_13_fu_1000_p3);

assign select_ln318_18_fu_1111_p3 = ((or_ln318_5_fu_1097_p2[0:0] === 1'b1) ? select_ln339_5_fu_1089_p3 : select_ln318_14_fu_1008_p3);

assign select_ln318_19_fu_1309_p3 = ((or_ln318_9_fu_1303_p2[0:0] === 1'b1) ? tmp_24_fu_1281_p4 : select_ln318_15_fu_1128_p3);

assign select_ln318_1_fu_498_p3 = ((or_ln318_fu_484_p2[0:0] === 1'b1) ? add_ln703_15_fu_456_p2 : x_l_FH_V_fu_412_p3);

assign select_ln318_20_fu_1317_p3 = ((or_ln318_9_fu_1303_p2[0:0] === 1'b1) ? sub_ln703_7_fu_1222_p2 : select_ln318_16_fu_1134_p3);

assign select_ln318_21_fu_1325_p3 = ((or_ln318_9_fu_1303_p2[0:0] === 1'b1) ? add_ln703_7_fu_1264_p2 : select_ln318_17_reg_2247);

assign select_ln318_22_fu_1332_p3 = ((or_ln318_9_fu_1303_p2[0:0] === 1'b1) ? select_ln339_6_fu_1274_p3 : select_ln318_18_reg_2257);

assign select_ln318_23_fu_1500_p3 = ((or_ln318_16_fu_1494_p2[0:0] === 1'b1) ? tmp_25_fu_1473_p4 : select_ln318_19_reg_2266);

assign select_ln318_24_fu_1507_p3 = ((or_ln318_16_fu_1494_p2[0:0] === 1'b1) ? sub_ln703_9_fu_1426_p2 : select_ln318_20_reg_2272);

assign select_ln318_25_fu_1514_p3 = ((or_ln318_16_fu_1494_p2[0:0] === 1'b1) ? add_ln703_9_fu_1456_p2 : select_ln318_21_reg_2278);

assign select_ln318_26_fu_1521_p3 = ((or_ln318_16_fu_1494_p2[0:0] === 1'b1) ? select_ln339_7_fu_1466_p3 : select_ln318_22_reg_2288);

assign select_ln318_27_fu_1717_p3 = ((or_ln318_19_reg_2340[0:0] === 1'b1) ? tmp_26_fu_1708_p4 : select_ln318_23_reg_2318);

assign select_ln318_28_fu_1683_p3 = ((or_ln318_19_fu_1677_p2[0:0] === 1'b1) ? sub_ln703_11_fu_1613_p2 : select_ln318_24_fu_1507_p3);

assign select_ln318_29_fu_1723_p3 = ((or_ln318_19_reg_2340[0:0] === 1'b1) ? add_ln703_11_fu_1703_p2 : select_ln318_25_reg_2324);

assign select_ln318_2_fu_506_p3 = ((or_ln318_fu_484_p2[0:0] === 1'b1) ? sub_ln703_fu_473_p2 : select_ln488_5_reg_2123);

assign select_ln318_30_fu_1691_p3 = ((or_ln318_19_fu_1677_p2[0:0] === 1'b1) ? select_ln339_8_fu_1657_p3 : select_ln318_26_fu_1521_p3);

assign select_ln318_31_fu_1912_p3 = ((or_ln318_22_reg_2383[0:0] === 1'b1) ? tmp_27_fu_1903_p4 : select_ln318_27_reg_2362);

assign select_ln318_32_fu_1918_p3 = ((or_ln318_22_reg_2383[0:0] === 1'b1) ? sub_ln703_13_fu_1899_p2 : select_ln318_28_reg_2346_pp0_iter6_reg);

assign select_ln318_33_fu_1924_p3 = ((or_ln318_22_reg_2383[0:0] === 1'b1) ? add_ln703_13_reg_2378 : select_ln318_29_reg_2368);

assign select_ln318_34_fu_1885_p3 = ((or_ln318_22_fu_1879_p2[0:0] === 1'b1) ? select_ln339_9_fu_1860_p3 : select_ln318_30_reg_2353);

assign select_ln318_35_fu_2032_p3 = ((or_ln318_25_fu_2026_p2[0:0] === 1'b1) ? tmp_29_fu_2004_p4 : select_ln318_31_fu_1912_p3);

assign select_ln318_3_fu_656_p3 = ((or_ln318_1_reg_2172[0:0] === 1'b1) ? tmp_18_fu_647_p4 : select_ln318_reg_2156);

assign select_ln318_4_fu_627_p3 = ((or_ln318_1_fu_621_p2[0:0] === 1'b1) ? sub_ln703_1_fu_577_p2 : select_ln318_1_fu_498_p3);

assign select_ln318_5_fu_662_p3 = ((or_ln318_1_reg_2172[0:0] === 1'b1) ? sub_ln703_2_reg_2167 : select_ln318_2_reg_2162);

assign select_ln318_6_fu_772_p3 = ((or_ln318_2_fu_766_p2[0:0] === 1'b1) ? tmp_20_fu_739_p4 : select_ln318_3_fu_656_p3);

assign select_ln318_7_fu_780_p3 = ((or_ln318_2_fu_766_p2[0:0] === 1'b1) ? sub_ln703_3_fu_714_p2 : select_ln318_4_reg_2178);

assign select_ln318_8_fu_787_p3 = ((or_ln318_2_fu_766_p2[0:0] === 1'b1) ? sub_ln703_4_fu_733_p2 : select_ln318_5_fu_662_p3);

assign select_ln318_9_fu_882_p3 = ((or_ln318_3_reg_2228[0:0] === 1'b1) ? tmp_21_fu_873_p4 : select_ln318_6_reg_2196);

assign select_ln318_fu_490_p3 = ((or_ln318_fu_484_p2[0:0] === 1'b1) ? 11'd1024 : 11'd0);

assign select_ln339_1_fu_589_p3 = ((icmp_ln1495_1_fu_571_p2[0:0] === 1'b1) ? add_ln703_1_fu_583_p2 : select_ln318_2_fu_506_p3);

assign select_ln339_2_fu_725_p3 = ((icmp_ln1495_2_fu_709_p2[0:0] === 1'b1) ? add_ln703_2_fu_719_p2 : select_ln318_5_fu_662_p3);

assign select_ln339_3_fu_868_p3 = ((icmp_ln1495_3_reg_2213[0:0] === 1'b1) ? add_ln703_3_reg_2223 : select_ln318_8_reg_2207);

assign select_ln339_4_fu_950_p3 = ((icmp_ln1495_4_fu_932_p2[0:0] === 1'b1) ? add_ln703_4_fu_944_p2 : select_ln318_11_fu_893_p3);

assign select_ln339_5_fu_1089_p3 = ((xor_ln331_fu_1065_p2[0:0] === 1'b1) ? add_ln703_6_fu_1083_p2 : select_ln318_14_fu_1008_p3);

assign select_ln339_6_fu_1274_p3 = ((or_ln331_fu_1244_p2[0:0] === 1'b1) ? add_ln703_8_fu_1269_p2 : select_ln318_18_reg_2257);

assign select_ln339_7_fu_1466_p3 = ((or_ln331_1_fu_1445_p2[0:0] === 1'b1) ? add_ln703_10_fu_1461_p2 : select_ln318_22_reg_2288);

assign select_ln339_8_fu_1657_p3 = ((or_ln331_2_fu_1637_p2[0:0] === 1'b1) ? add_ln703_12_fu_1651_p2 : select_ln318_26_fu_1521_p3);

assign select_ln339_9_fu_1860_p3 = ((or_ln331_3_fu_1829_p2[0:0] === 1'b1) ? add_ln703_14_fu_1855_p2 : select_ln318_30_reg_2353);

assign select_ln339_fu_467_p3 = ((icmp_ln1495_reg_2132[0:0] === 1'b1) ? add_ln703_fu_462_p2 : select_ln488_5_reg_2123);

assign select_ln488_1_fu_242_p3 = ((icmp_ln488_fu_210_p2[0:0] === 1'b1) ? x_l_I_V_fu_188_p1 : p_Result_s_26_fu_222_p5);

assign select_ln488_2_fu_316_p3 = ((icmp_ln488_1_fu_282_p2[0:0] === 1'b1) ? select_ln488_fu_234_p3 : tmp_9_fu_306_p4);

assign select_ln488_3_fu_324_p3 = ((icmp_ln488_1_fu_282_p2[0:0] === 1'b1) ? select_ln488_1_fu_242_p3 : p_Result_30_1_fu_294_p5);

assign select_ln488_4_fu_428_p3 = ((icmp_ln488_2_reg_2118[0:0] === 1'b1) ? select_ln488_2_reg_2112 : tmp_10_fu_419_p4);

assign select_ln488_5_fu_372_p3 = ((icmp_ln488_2_fu_348_p2[0:0] === 1'b1) ? select_ln488_3_fu_324_p3 : p_Result_30_2_fu_360_p5);

assign select_ln488_fu_234_p3 = ((icmp_ln488_fu_210_p2[0:0] === 1'b1) ? 3'd0 : 3'd4);

assign sub_ln248_1_fu_354_p2 = (trunc_ln612_fu_340_p1 - zext_ln488_1_fu_344_p1);

assign sub_ln248_fu_288_p2 = (p_Result_28_1_fu_268_p4 - zext_ln488_fu_278_p1);

assign sub_ln703_10_fu_1451_p2 = (p_neg_7_reg_2313 - trunc_ln708_9_fu_1381_p4);

assign sub_ln703_11_fu_1613_p2 = (select_ln318_24_fu_1507_p3 - mul_FL_V_8_fu_1557_p3);

assign sub_ln703_12_fu_1699_p2 = (p_neg_8_reg_2335 - trunc_ln708_10_reg_2330);

assign sub_ln703_13_fu_1899_p2 = (select_ln318_28_reg_2346_pp0_iter6_reg - mul_FL_V_9_reg_2373);

assign sub_ln703_14_fu_1843_p2 = (p_neg_9_fu_1835_p3 - trunc_ln708_11_fu_1749_p4);

assign sub_ln703_1_fu_577_p2 = (select_ln318_1_fu_498_p3 - trunc_ln708_4_fu_545_p4);

assign sub_ln703_2_fu_597_p2 = (select_ln339_1_fu_589_p3 - zext_ln1494_1_fu_555_p1);

assign sub_ln703_3_fu_714_p2 = (select_ln318_4_reg_2178 - trunc_ln708_6_fu_684_p4);

assign sub_ln703_4_fu_733_p2 = (select_ln339_2_fu_725_p3 - zext_ln1494_2_fu_693_p1);

assign sub_ln703_5_fu_832_p2 = (select_ln318_7_fu_780_p3 - trunc_ln708_8_fu_805_p4);

assign sub_ln703_6_fu_938_p2 = (select_ln318_10_fu_888_p3 - trunc_ln708_s_fu_909_p5);

assign sub_ln703_7_fu_1222_p2 = (select_ln318_16_fu_1134_p3 - mul_FL_V_6_fu_1170_p3);

assign sub_ln703_8_fu_1258_p2 = (p_neg_6_fu_1250_p3 - trunc_ln708_7_fu_1161_p4);

assign sub_ln703_9_fu_1426_p2 = (select_ln318_20_reg_2272 - mul_FL_V_7_reg_2302);

assign sub_ln703_fu_473_p2 = (select_ln339_fu_467_p3 - zext_ln1494_fu_442_p1);

always @ (*) begin
    tmp_10_fu_419_p4 = select_ln488_2_reg_2112;
    tmp_10_fu_419_p4[32'd0] = |(1'd1);
end

assign tmp_11_fu_380_p4 = {{x_V_int_reg[9:8]}};

assign tmp_12_fu_1538_p4 = {{select_ln318_23_fu_1500_p3[10:8]}};

assign tmp_13_fu_1739_p4 = {{select_ln318_27_fu_1717_p3[10:9]}};

assign tmp_14_fu_2076_p4 = {{res_FH_V_fu_2050_p2[10:1]}};

assign tmp_16_fu_396_p4 = {{x_V_int_reg[9:8]}};

always @ (*) begin
    tmp_18_fu_647_p4 = select_ln318_reg_2156;
    tmp_18_fu_647_p4[32'd9] = |(1'd1);
end

assign tmp_1_fu_260_p3 = {{p_Result_25_1_fu_250_p4}, {1'd1}};

always @ (*) begin
    tmp_20_fu_739_p4 = select_ln318_3_fu_656_p3;
    tmp_20_fu_739_p4[32'd8] = |(1'd1);
end

always @ (*) begin
    tmp_21_fu_873_p4 = select_ln318_6_reg_2196;
    tmp_21_fu_873_p4[32'd7] = |(1'd1);
end

always @ (*) begin
    tmp_22_fu_958_p4 = select_ln318_9_fu_882_p3;
    tmp_22_fu_958_p4[32'd6] = |(1'd1);
end

always @ (*) begin
    tmp_23_fu_1119_p4 = select_ln318_12_reg_2235;
    tmp_23_fu_1119_p4[32'd5] = |(1'd1);
end

always @ (*) begin
    tmp_24_fu_1281_p4 = select_ln318_15_fu_1128_p3;
    tmp_24_fu_1281_p4[32'd4] = |(1'd1);
end

always @ (*) begin
    tmp_25_fu_1473_p4 = select_ln318_19_reg_2266;
    tmp_25_fu_1473_p4[32'd3] = |(1'd1);
end

always @ (*) begin
    tmp_26_fu_1708_p4 = select_ln318_23_reg_2318;
    tmp_26_fu_1708_p4[32'd2] = |(1'd1);
end

always @ (*) begin
    tmp_27_fu_1903_p4 = select_ln318_27_reg_2362;
    tmp_27_fu_1903_p4[32'd1] = |(1'd1);
end

assign tmp_28_fu_1941_p3 = select_ln318_31_fu_1912_p3[32'd10];

always @ (*) begin
    tmp_29_fu_2004_p4 = select_ln318_31_fu_1912_p3;
    tmp_29_fu_2004_p4[32'd0] = |(1'd1);
end

assign tmp_2_fu_332_p3 = {{select_ln488_2_fu_316_p3}, {1'd1}};

assign tmp_3_fu_1141_p4 = {{select_ln318_15_fu_1128_p3[5:4]}};

assign tmp_4_fu_1339_p4 = {{select_ln318_19_fu_1309_p3[6:3]}};

assign tmp_5_fu_1528_p4 = {{select_ln318_23_fu_1500_p3[7:2]}};

assign tmp_6_fu_1729_p4 = {{select_ln318_27_fu_1717_p3[8:1]}};

assign tmp_8_fu_523_p4 = {{select_ln488_4_fu_428_p3[2:1]}};

always @ (*) begin
    tmp_9_fu_306_p4 = select_ln488_fu_234_p3;
    tmp_9_fu_306_p4[32'd1] = |(1'd1);
end

assign tmp_fu_196_p4 = {{x_V_int_reg[15:14]}};

assign tmp_s_fu_1151_p4 = {{select_ln318_15_fu_1128_p3[10:6]}};

assign trunc_ln103_fu_1929_p1 = select_ln318_31_fu_1912_p3[9:0];

assign trunc_ln612_fu_340_p1 = select_ln488_3_fu_324_p3[4:0];

assign trunc_ln708_10_fu_1548_p4 = {{{{5'd0}, {select_ln488_4_reg_2142_pp0_iter4_reg}}}, {tmp_12_fu_1538_p4}};

assign trunc_ln708_11_fu_1749_p4 = {{{{6'd0}, {select_ln488_4_reg_2142_pp0_iter5_reg}}}, {tmp_13_fu_1739_p4}};

assign trunc_ln708_12_fu_1949_p4 = {{{{7'd0}, {select_ln488_4_reg_2142_pp0_iter6_reg}}}, {tmp_28_fu_1941_p3}};

assign trunc_ln708_13_fu_643_p1 = select_ln488_4_fu_428_p3[1:0];

assign trunc_ln708_1_fu_434_p3 = {{4'd0}, {select_ln488_4_fu_428_p3}};

assign trunc_ln708_2_fu_1026_p4 = {{{{2'd0}, {select_ln488_4_reg_2142_pp0_iter2_reg}}}, {p_Result_34_5_fu_1016_p4}};

assign trunc_ln708_3_fu_533_p3 = {{5'd0}, {tmp_8_fu_523_p4}};

assign trunc_ln708_4_fu_545_p4 = {{{trunc_ln708_fu_541_p1}, {p_Result_34_1_fu_513_p4}}, {8'd128}};

assign trunc_ln708_5_fu_677_p3 = {{6'd0}, {tmp_19_reg_2186}};

assign trunc_ln708_6_fu_684_p4 = {{{trunc_ln708_13_reg_2191}, {p_Result_34_2_fu_667_p4}}, {6'd32}};

assign trunc_ln708_7_fu_1161_p4 = {{{{3'd0}, {select_ln488_4_reg_2142_pp0_iter3_reg}}}, {tmp_s_fu_1151_p4}};

assign trunc_ln708_8_fu_805_p4 = {{{select_ln488_4_reg_2142}, {p_Result_34_3_fu_795_p4}}, {4'd8}};

assign trunc_ln708_9_fu_1381_p4 = {{{{4'd0}, {select_ln488_4_reg_2142_pp0_iter4_reg}}}, {tmp_7_reg_2297}};

assign trunc_ln708_fu_541_p1 = select_ln488_4_fu_428_p3[0:0];

assign trunc_ln708_s_fu_909_p5 = {{{{{{1'd0}, {select_ln488_4_reg_2142_pp0_iter2_reg}}}, {p_Result_34_4_fu_899_p4}}}, {2'd2}};

assign trunc_ln731_fu_192_p1 = x_V_int_reg[9:0];

assign trunc_ln_fu_178_p4 = {{x_V_int_reg[15:10]}};

assign x_l_FH_V_fu_412_p3 = {{trunc_ln731_reg_2107}, {1'd0}};

assign x_l_I_V_fu_188_p1 = trunc_ln_fu_178_p4;

assign xor_ln318_1_fu_1482_p2 = (or_ln318_11_fu_1420_p2 ^ 1'd1);

assign xor_ln318_2_fu_1665_p2 = (or_ln318_12_fu_1607_p2 ^ 1'd1);

assign xor_ln318_3_fu_1867_p2 = (or_ln318_13_fu_1805_p2 ^ 1'd1);

assign xor_ln318_4_fu_2014_p2 = (or_ln318_14_fu_1998_p2 ^ 1'd1);

assign xor_ln318_5_fu_609_p2 = (icmp_ln318_1_fu_603_p2 ^ 1'd1);

assign xor_ln318_6_fu_754_p2 = (icmp_ln318_2_fu_749_p2 ^ 1'd1);

assign xor_ln318_7_fu_850_p2 = (icmp_ln318_3_fu_844_p2 ^ 1'd1);

assign xor_ln318_8_fu_974_p2 = (icmp_ln318_4_fu_968_p2 ^ 1'd1);

assign xor_ln318_fu_1291_p2 = (or_ln318_6_fu_1216_p2 ^ 1'd1);

assign xor_ln331_fu_1065_p2 = (icmp_ln331_fu_1059_p2 ^ 1'd1);

assign xor_ln703_fu_1071_p2 = (trunc_ln708_2_fu_1026_p4 ^ 11'd2047);

assign zext_ln1192_fu_2040_p1 = select_ln318_35_fu_2032_p3;

assign zext_ln1494_1_fu_555_p1 = trunc_ln708_3_fu_533_p3;

assign zext_ln1494_2_fu_693_p1 = trunc_ln708_5_fu_677_p3;

assign zext_ln1494_fu_442_p1 = trunc_ln708_1_fu_434_p3;

assign zext_ln248_fu_206_p1 = tmp_fu_196_p4;

assign zext_ln488_1_fu_344_p1 = tmp_2_fu_332_p3;

assign zext_ln488_fu_278_p1 = tmp_1_fu_260_p3;

always @ (posedge ap_clk) begin
    select_ln318_reg_2156[9:0] <= 10'b0000000000;
    select_ln318_4_reg_2178[0] <= 1'b0;
    select_ln318_7_reg_2202[0] <= 1'b0;
    sub_ln703_5_reg_2218[0] <= 1'b0;
    select_ln318_20_reg_2272[7:0] <= 8'b00000000;
    mul_FL_V_7_reg_2302[6:0] <= 7'b1000000;
    trunc_ln708_10_reg_2330[10:6] <= 5'b00000;
    select_ln318_28_reg_2346[3:0] <= 4'b0000;
    select_ln318_28_reg_2346_pp0_iter6_reg[3:0] <= 4'b0000;
    mul_FL_V_9_reg_2373[2:0] <= 3'b100;
end

endmodule //sqrt_fixed_16_6_s
